### ISSUE TITLE
Announce dlang/projects

### ISSUE THREAD

**Issue by burner** [dlang/projects#35]
## Description
Write an announcement of dlang/projects on the forums

## Point of Contact
@wilzbach @thewilsonator @burner @atilaneves 

## References

<NG discussions, GitHub PRs, Bugzilla issues, ...>

**Comment by wilzbach** [comment]
Let's clarify the README first?
See e.g. https://github.com/dlang/projects/pull/36

**Comment by wilzbach** [comment]
Also, we should go through all the copied projects and make sure that they are:
- still relevant
- have at least of "Point of Contact" (PoC) there

Motivation:
- otherwise not really helpful to students (whom to contact, relevance, etc.)
- we want to provide good examples for the community to follow (i.e. setting the gold standard)

Alternatively, we could also ask the community to be a PoC for these projects and if there's no one stepping up in the next 1-3 months and no up-votes, we close them?

**Comment by burner** [comment]
I think we should 
* rename vision to approved (IMHO vision is to vage) 
* add a meta tag to filter on issues that related to the organisation of this repo

thoughts?

**Comment by wilzbach** [comment]
> rename vision to approved (IMHO vision is to vage)

Walter started to use "vision" for some of his PRs, hence the name of the label.

https://github.com/dlang/dmd/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3AVision+
https://github.com/dlang/phobos/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3AVision+

"approved" is problematic, because it implies a bit that a project needs to be approved.
I don't think "vision" is too bad, especially because it's now explained in the README, but how about "DLF vision", "leadership vision", "DLF priority"?

> add a meta tag to filter on issues that related to the organisation of this repo

:+1:

**Comment by burner** [comment]
I like "leadership vision" the best

**Comment by wilzbach** [comment]
> I like "leadership vision" the best

OK -> PR: https://github.com/dlang/projects/pull/39

**Comment by wilzbach** [comment]
Here's a proposed announcement:

----
Hi everyone,

at DConf one common concern raised was that it's hard to track the progress on important high-level projects. Furthermore, its also hard for interested contributors to find such projects and judge which ones  really matter to the D community. Lastly, the existing wiki pages (wishlist, GSoC project list, vision document etc.) were chronically out-of-date.

Hence, during DCong we created the dlang/projects repository - a collection of impactful projects in the D ecosystem:

-> https://github.com/dlang/projects

We have seeded the repository with the existing projects from the wiki and encourage everyone to vote on them (via GitHub reactions) or express their opinion as this will greatly help us to judge which projects are important to the community.
-> vote for projects that matter to you/your company

Furthermore, everyone is invited to submit new projects to this repository. However, please keep in mind that this repository tries to collect high-level goals and project. A good rule of thumb is that if a project can't be split into smaller parts, it might belong to its respective issue tracker.
-> propose projects that matter to you/your company

Projects marked with the "leadership vision" label are vision projects of the D Language Foundation. These projects are seen as key projects to D's success by the leadership.

As many of the projects ideas will make good GSoC projects, we will also this repository as an idea list for future GSoC/SAoC. More details on this will be announced later.

Happy voting!
----

If no one objects to this, I would post it on NG.announce on Thursday evening.

**Comment by Basile-z** [comment]
> Hence, during DCong we created the dlang/projects repository - a collection of impactful projects in the D ecosystem:

Dcong for D congress I presume ?

**Comment by wilzbach** [comment]
Announced -> https://forum.dlang.org/post/ujsicblucigfkyxyinca@forum.dlang.org

**Comment by burner** [comment]
@wilzbach thank you
